version: '3.8'
services:

  backend:

    build: ./farm_backend
    ports: 
      - "8000:8000"
    env_file:
      - ./farm_backend/.env

  frontend: 

    build: ./farm-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    
      


